# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "jborean93/WindowsServer2019"
  config.vm.hostname = "TEST-PC"
  config.vm.network :private_network, ip: "192.168.56.50"
end
